os: osx
osx_image: xcode26.1
language: swift
script:
  - xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO macosx - destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
  - xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO iphonesimulator - destination "platform=iOS Simulator,OS=12.2,name=iphone" ONLY_ACTIVE_ARCH=YES
